instream: pass fileName by reference
... to eliminate unnecessary string copies

Suggested by Coverity:
```
Error: COPY_INSTEAD_OF_MOVE:
src/cslinker.cc:236:29: copy_constructor_call: "fnCwe" is passed-by-value as parameter to "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const &)", when it could be moved instead.
src/cslinker.cc:236:29: remediation: Use "std::move(""fnCwe"")" instead of "fnCwe".

Error: COPY_INSTEAD_OF_MOVE:
src/cslinker.cc:249:29: copy_constructor_call: "fnImp" is passed-by-value as parameter to "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const &)", when it could be moved instead.
src/cslinker.cc:249:29: remediation: Use "std::move(""fnImp"")" instead of "fnImp".
```

Related: https://github.com/csutils/csdiff/pull/216