packaging: do not use `%py_provides` in epel-7 builds
If the buildroot contains outdated packages that do not yet contain
definition of the macro, it causes the build of csdiff to fail with:
```
error: line 90: Unknown tag: %py_provides    python3-csdiff
```

This partially reverts commit df5c63fbbc676220c0c13e3d3e4070beeab0489f.

Fixes: commit f16db5adb1c0ccb2619c0e3d11badbc606796ae1
Closes: https://github.com/csutils/csdiff/pull/203