cmake: declare the pycsdiff target as a MODULE library
... to mark the intent that it is meant to be used by `dlopen` only.

Consequently, this forces the library to always use the `.so` suffix
which fixes the following test failure on macOS because Python ignores
shared libraries with the native `.dylib` suffix.
```
pycsdiff_py3......................................***Failed    0.02 sec
Traceback (most recent call last):
      File "<string>", line 1, in <module>
      ModuleNotFoundError: No module named 'pycsdiff'
```