gcc-parser.cc: fix missing initialization caught by Coverity
Error: UNINIT_CTOR (CWE-456):
csdiff-0.20131127_541b54f/gcc-parser.cc:168: member_decl: Class member declaration for "lastTok_".
csdiff-0.20131127_541b54f/gcc-parser.cc:159: uninit_member: Non-static class member "lastTok_" is not initialized in this constructor nor in any functions that it calls.