csparser: make the reTrailLoc_ regex stricter
... so that it does not trigger on similar constructions in code
snippets contained in comments.  The following defecet detected
by Pylint on calamari-server-1.3.4-1.el7cp caused a major problem
to csparser:

    Error: PROSPECTOR_WARNING:
    /opt/calamari/venv/lib/python2.7/site-packages/graphite/thirdparty/pyparsing.py:795:24: W0613[pylint]: Unused argument 's'
    #  793|                       return f(f.__call__.__self__, s,l,t)
    #  794|               if numargs == 2:
    #  795|->                 def tmp(s,l,t):
    #  796|                       return f(l,t)
    #  797|               elif numargs == 1: