packaging: do not use `%py_provides` for Python 2
The macro is not available in EPEL-7 buildroot and causes the build
of csdiff to fail:
```
error: line 79: Unknown tag: %py_provides    python2-csdiff
```

This partially reverts commit df5c63fbbc676220c0c13e3d3e4070beeab0489f.

Closes: https://github.com/csutils/csdiff/pull/202