writer-json-simple: provide csdiff/v1 fingerprints
... when the line content in the `csgrep --embed-context` format
is available.

Out of the 1783 fingerprints generated for the csgrep regression tests
we got 115 collisions, which need to be analyzed.  Some of them look
undesired as, for example:
```
Error: CERT EXP40-C (CWE-758):
wget-1.21.1/src/http.c:256: cert_exp40_c_violation: Casting pointer "value" with type "char const *" to type "void *" allows an object defined with a const-qualified type to be modified through use of an lvalue with non-const-qualified type.
 # 254|             release_header (hdr);
 # 255|             hdr->name = (void *)name;
 # 256|->           hdr->value = (void *)value;
 # 257|             hdr->release_policy = release_policy;
 # 258|             return;

Error: CERT EXP40-C (CWE-758):
wget-1.21.1/src/http.c:271: cert_exp40_c_violation: Casting pointer "value" with type "char const *" to type "void *" allows an object defined with a const-qualified type to be modified through use of an lvalue with non-const-qualified type.
 # 269|     hdr = &req->headers[req->hcount++];
 # 270|     hdr->name = (void *)name;
 # 271|->   hdr->value = (void *)value;
 # 272|     hdr->release_policy = release_policy;
 # 273|   }
```

Related: https://github.com/csutils/csdiff/issues/98