cmake: enable C++11 explicitly
... to make the code compile again with gcc-4.8.x.  The previous commit
made it fail with:

csfilter.cc: In constructor ‘MsgFilter::Private::Private()’:
csfilter.cc:120:9: error: in C++98 ‘pylintCheckers’ must be initialized by constructor, not by ‘{...}’
         };
         ^
In file included from /usr/include/c++/4.8.2/bits/stl_tempbuf.h:60:0,
                 from /usr/include/c++/4.8.2/bits/stl_algo.h:62,
                 from /usr/include/c++/4.8.2/algorithm:62,
                 from /usr/include/boost/regex/v4/regex_workaround.hpp:33,
                 from /usr/include/boost/regex/v4/regex.hpp:32,
                 from /usr/include/boost/regex.hpp:31,
                 from csfilter.cc:24:
/usr/include/c++/4.8.2/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, const _T2&) [with _T1 = std::basic_string<char>; _T2 = char]’:
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*; bool _TrivialValueTypes = false]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:117:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*]’
/usr/include/c++/4.8.2/bits/stl_uninitialized.h:258:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = const char*; _ForwardIterator = std::basic_string<char>*; _Tp = std::basic_string<char>]’
/usr/include/c++/4.8.2/bits/stl_vector.h:1206:27:   required from ‘void std::vector<_Tp, _Alloc>::_M_range_initialize(_ForwardIterator, _ForwardIterator, std::forward_iterator_tag) [with _ForwardIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >]’
/usr/include/c++/4.8.2/bits/stl_vector.h:1177:56:   required from ‘void std::vector<_Tp, _Alloc>::_M_initialize_dispatch(_InputIterator, _InputIterator, std::__false_type) [with _InputIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >]’
/usr/include/c++/4.8.2/bits/stl_vector.h:404:55:   required from ‘std::vector<_Tp, _Alloc>::vector(_InputIterator, _InputIterator, const allocator_type&) [with _InputIterator = const char*; _Tp = std::basic_string<char>; _Alloc = std::allocator<std::basic_string<char> >; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<std::basic_string<char> >]’
csfilter.cc:120:9:   required from here
/usr/include/c++/4.8.2/bits/stl_construct.h:83:7: error: invalid conversion from ‘char’ to ‘const char*’ [-fpermissive]
       ::new(static_cast<void*>(__p)) _T1(__value);
       ^
In file included from /usr/include/c++/4.8.2/string:53:0,
                 from csfilter.hh:24,
                 from csfilter.cc:20:
/usr/include/c++/4.8.2/bits/basic_string.tcc:212:5: error:   initializing argument 1 of ‘std::basic_string<_CharT, _Traits, _Alloc>::basic_string(const _CharT*, const _Alloc&) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]’ [-fpermissive]
     basic_string<_CharT, _Traits, _Alloc>::
     ^